In [2]:
#  정수형 series
import pandas as pd
s=pd.Series([1,2,3,4,8])
print(s)


0    1
1    2
2    3
3    4
4    8
dtype: int64


In [3]:
#  실수형 series
s = pd.Series([1.3,2.5,3.6,2.3,1.2])
print(s)

0    1.3
1    2.5
2    3.6
3    2.3
4    1.2
dtype: float64


In [4]:
#  실수형 series
s = pd.Series([1,2.5,3,8.9,7])
print(s)

0    1.0
1    2.5
2    3.0
3    8.9
4    7.0
dtype: float64


In [5]:
# 인덱스 지정
s = pd.Series([1,2.5,3,8.9,7], index=['a','b','c','d','e'])
print(s)

a    1.0
b    2.5
c    3.0
d    8.9
e    7.0
dtype: float64


In [9]:
import numpy as np
a= np.array([1,2,3])
print(a)
b = np.zeros(5)
print(b)
c = np.ones((2,3))
print(c)

[1 2 3]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])
# 요소별 합
print(np.add(a, b))
# 요소별 곱
print(np.multiply(a, b))
# 어레이값의 평균
print(np.mean(b))

[5 5 5 5]
[4 6 6 4]
2.5


In [16]:
# 0과 1사이에서 균일한 분포를 갖는 숫자 샘플링
a = np.random.rand(2,5)
print(a)
# 표준정규분포를 갖는 숫자들 샘플링
b = np.random.randn(2,4)
print(b)

[[0.83537908 0.43676776 0.97503498 0.12526273 0.88013959]
 [0.38987307 0.73916394 0.89431216 0.32482145 0.81221244]]
[[ 0.11321486 -0.44240349  0.09501083  3.11365354]
 [-1.24604839 -2.35705693 -0.52041559 -1.48935644]]


In [19]:
# 파이
a = np.pi
print(a)
# 오일러 상수
b = np.e
print(b)

3.141592653589793
2.718281828459045


In [22]:
a = np.array([1.2,5,6,8])
print(type(a))
print(a)
# 어레이 요소의 자료형을 알고싶을때
print(a.dtype)

<class 'numpy.ndarray'>
[1.2 5.  6.  8. ]
float64


In [24]:
a = np.array([(1,2,3,4),(1,2,3,4)])
print(a)


[[1 2 3 4]
 [1 2 3 4]]


In [25]:
# 타입 지정
a = np.array(([1,2,3],[4,5,6]),dtype = complex)
print(a)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
